### ISSUE TITLE
No Windows support for scripty

### ISSUE THREAD

**Issue by ShekharNain** [mike-works/typescript-fundamentals#110]
- [x] **System Information**
  - [ ] Browser type and version
  - [ ] OS type and version
  - [x] WINDOWS: be sure to indicate which terminal you're using -- (i.e., cmd.exe, powershell, git- bash, cygwin, Ubuntu via windows subsystem for linux, etc...)
 cmd.exe, powershell & git -bash
  - [x] Node version
8.11.3
  - [ ] Any error messages that may be in the console where you ran npm start
  - [ ] Any error messages in the JS console

- [x] **Describe the bug**
yarn test throwing below error in windows because of scripty:

internal/child_process.js:323    throw errnoException(err, 'spawn');
    ^
Error: spawn UNKNOWN
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)

- [ ] **To Reproduce**

- [ ] **Expected behavior**

- [x] **Screenshots (optional)**
PFA the screenshots.
![image](https://user-images.githubusercontent.com/15901915/46580859-98845480-ca4a-11e8-8987-cfd479e333ac.png)

- [ ] **Additional context (optional)**

**Comment by microcipcip** [comment]
Thanks @ShekharNain, your fix worked.

**Comment by mike-north** [comment]
Closing this issue because we've released a new version of the TypeScript course, where this is not a problem anymore
