### ISSUE TITLE
autocomplete-sfc/ App JS Error Super Arguments & general Dependency updates

### ISSUE THREAD

**Issue by NickFoden** [mike-works/typescript-fundamentals#136]
- [ Mac OS 10.14.1 - MBP 2017] **System Information**
  - [Chrome  70.0.3538.77 (64-bit)] Browser type and version
  - [ Mac OS 10.14.1] OS type and version
  - [VSCode ] WINDOWS: be sure to indicate which terminal you're using -- (i.e., cmd.exe, powershell, git- bash, cygwin, Ubuntu via windows subsystem for linux, etc...)
  - [10.0.0 ] Node version
  - [Version 3.1.6] Typescript version
  - [ERROR in [at-loader] ./exercises/autocomplete-sfc/src/app.tsx:11:5
    TS2554: Expected 1-2 arguments, but got 0. ] Any error messages that may be in the console where you ran npm start
  - [ ERROR in [at-loader] ./exercises/autocomplete-sfc/src/app.tsx:11:5
    TS2554: Expected 1-2 arguments, but got 0.] Any error messages in the JS console

- [ ] **Describe the bug**

Initial run start project would not compile following the error messages i npm installed
extract-text-webpack-plugin and babel loader

My current package.json here -> [package.json](https://github.com/NickFoden/tscript/blob/master/package.json)

**Then:** 
In autocomplete-sfc lesson in app.tsx the super() call has red squiggle underline as the error location

passing an object into super seems to fix the issue. 
    super({});

And had to pass ?: to each item in the interface PlaceDetails to get render:

[My file here](https://github.com/NickFoden/tscript/blob/master/exercises/autocomplete-sfc/src/utils/places.ts)

- [ ] **To Reproduce**
1. Go to https://frontendmasters.com/courses/typescript/challenge-7-autocomplete-part-1/
2. npm start autocomplete-sfc
3. See error in console/in browser

- [ ] **Expected behavior**
Expected initial compile to compile/render to start the lesson with instructor. 

- [ ] **Additional context (optional)**

**Comment by NickFoden** [comment]
Ok yeah same thing next lesson. Adding the {} to super lets it compile and clears arguments warning. I think this might be because of my current typescript version. 
super({});

**Comment by mike-north** [comment]
Downgraded react to v15, and this becomes a non-issue as expected c6c6f3e
