### ISSUE TITLE
dependency problem; unable to get test environment working

### ISSUE THREAD

**Issue by jccartwright** [mike-works/typescript-fundamentals#184]
- [ ] **System Information**
  - [ ] Browser type and version
Chrome 71.0.3578.98
  - [ ] OS type and version
MacOS 10.13.06
  - [ ] WINDOWS: be sure to indicate which terminal you're using -- (i.e., cmd.exe, powershell, git- bash, cygwin, Ubuntu via windows subsystem for linux, etc...)
  - [ ] Node version
10.7.0
  - [ ] Any error messages that may be in the console where you ran npm start
  - [ ] Any error messages in the JS console

- [ ] **Describe the bug**

- [ ] **To Reproduce**
1. git clone https://github.com/mike-works/typescript-fundamentals tscript
2. cd tscript
3. yarn
4. See error:
yarn install v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

- [ ] **Expected behavior**
yarn to complete successfully.
 
- [ ] **Screenshots (optional)**

- [ ] **Additional context (optional)**

**Comment by the-nick-wilson** [comment]
I'm not sure if this is the best approach, but based on what I found [here](https://github.com/ahmadnassri/node-har-validator/issues/113), I just updated the relevant section in the yarn.lock file to 5.1.3.

So change this:

```
har-validator@~5.1.0:
  version "5.1.2"
  resolved "https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz#a3891924f815c88e41c7f31112079cfef5e129e5"
  integrity sha512-OFxb5MZXCUMx43X7O8LK4FKggEQx6yC5QPmOcBnYbJ9UjxEcMcrMbaR0af5HZpqeFopw2GwQRQi34ZXI7YLM5w==
  dependencies:
    ajv "^6.5.5"
    har-schema "^2.0.0"
```

To this:

```
har-validator@~5.1.3:
  version "5.1.3"
  resolved "https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz#a3891924f815c88e41c7f31112079cfef5e129e5"
  integrity sha512-OFxb5MZXCUMx43X7O8LK4FKggEQx6yC5QPmOcBnYbJ9UjxEcMcrMbaR0af5HZpqeFopw2GwQRQi34ZXI7YLM5w==
  dependencies:
    ajv "^6.5.5"
    har-schema "^2.0.0"
```

And try the yarn install command again and it should work. Basically it appears the har-validator package was tagged under the wrong version.

**Comment by jccartwright** [comment]
thanks for the prompt response. modifying the version does indeed seem to allow yarn to install dependencies correctly.  

However, I'm now wondering if the test script is working as expected.  For example 
cd exercises; npm test color-functions

does not run the tests for "color-functions".  It looks to me as if the scripts/test/index.sh should contain
  ./node_modules/.bin/jest --no-cache --watch $1
rather than
./node_modules/.bin/jest --no-cache --watch $2

**Comment by the-nick-wilson** [comment]
Hmm, I don't think you need to cd into the exercises directory. Did you try npm test color-functions from the base directory? Do you get an error when trying to run it?

**Comment by jccartwright** [comment]
Yes, the behavior is the same from the base directory.  It appears to me the problem is the positional parameter in the script, i.e.
  
  npm test junk color-functions

works OK as does modifying test/scripts/index.sh to contain:

  ./node_modules/.bin/jest --no-cache --watch $1

**Comment by the-nick-wilson** [comment]
Weird, I totally see what you mean, but mine works just fine with:

`npm test color-functions`

Even though my index.sh is:

`#!/bin/bash
./node_modules/.bin/jest --no-cache --watch $2`

I tried:

`npm test junk color-functions`

And that still works too.

**Comment by mike-north** [comment]
I just updated the lock file, with an upgrade to node-sass.

Before
```sh
yarn why har-validator

=> Found "har-validator@5.1.2"
info Reasons this module exists
   - "node-sass#request" depends on it
   - Hoisted from "node-sass#request#har-validator"
```

After
```sh
yarn why har-validator

=> Found "har-validator@5.1.3"
info Reasons this module exists
   - "node-sass#request" depends on it
   - Hoisted from "node-sass#request#har-validator"
```
