### ISSUE TITLE
Running npm test for specific module/suite is running all tests

### ISSUE THREAD

**Issue by the-other-nick-wilson** [mike-works/typescript-fundamentals#191]
- [X] **System Information**
  - [X] Browser type and version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
  - [X] OS type and version: MacOS X Mojave 10.14.2
  - [X] Node version: 6.5.0
  - [X] Any error messages that may be in the console where you ran npm start: None
  - [X] Any error messages in the JS console: None

- [X] **Describe the bug**
When trying to run specific module tests, it is running all test suites instead.

- [X] **To Reproduce**
1. Go to the root directory of the project.
2. Run: `npm test dealer`
3. Note the output which says:
```#!/bin/bash
./node_modules/.bin/jest --no-cache --watch $2
```
4. Note that all test suites ran:
```
Test Suites: 1 failed, 2 passed, 3 total
Tests:       8 failed, 24 passed, 32 total
Snapshots:   0 total
Time:        2.083s
Ran all test suites related to changed files.
```

- [X] **Expected behavior**
When running for a specific suite, it should obviously only run that suite. You can hack this by giving a dummy 1st argument to the "test" command: `npm test fjksdlfjds dealer` 

This results in only the dealer suite being ran:
![image](https://user-images.githubusercontent.com/11092367/51059789-a34f0800-15aa-11e9-9d33-68d6a27c7b92.png)

- [X] **Screenshots (optional)**
Screenshot of all tests being run:
![image](https://user-images.githubusercontent.com/11092367/51059745-7995e100-15aa-11e9-9d6b-566885a51067.png)

- [X] **Additional context**
See [this issue](https://github.com/mike-works/typescript-fundamentals/issues/184) which talks about the same thing near the bottom. I think the issue was closed addressing only the initial problem. Also see this [possibly related issue](https://github.com/mike-works/typescript-fundamentals/issues/29).

Perhaps the $2 argument in [scripts/test/index.sh](https://github.com/mike-works/typescript-fundamentals/blob/master/scripts/test/index.sh) is supposed to be $1?

**Comment by mike-north** [comment]
Closing this issue because we've released a new version of the TypeScript course, where this is not a problem anymore
