### ISSUE TITLE
localhost:3000 is blank

### ISSUE THREAD

**Issue by moontaekim** [mike-works/typescript-fundamentals#193]
Im following along on the autocomplete-sfc exercise. I got a new API key and included it into apikeys.js. When i run npm start autocomplete-sfc, i get a blank screen on localhost:3000. 
![screen shot 2019-01-15 at 3 17 58 pm](https://user-images.githubusercontent.com/40767464/51207452-ce05cd00-18d8-11e9-8fd0-3cf65ad660d0.png)

**Comment by mike-north** [comment]
any js console errors?

**Comment by moontaekim** [comment]
No errors. There was a yellow message that wanted me to add the API key so i added it and changed the name of the file as instructed. The message disappeared after that. I also wasn’t able to see the clock from the exercise before.

**Comment by mike-north** [comment]
Just tried w/ the latest dependencies

```sh
rm -rf node_modules && yarn install &&  npm run start --- autocomplete-sfc
```
and it works for me. 

If you open up devtools, do you see a network requests going out like I do?
<img width="1336" alt="screen shot 2019-01-15 at 1 41 11 pm" src="https://user-images.githubusercontent.com/558005/51211867-9d6b6680-18cb-11e9-9e3f-d79e7baeb035.png">

You could also try to hit the API directly with a URL like

http://localhost:3000/maps/api/place/autocomplete/json?types=establishment&input=donut

Does ☝️ work?

**Comment by moontaekim** [comment]
I ran rm -rf node_modules && yarn install &&  npm run start --- autocomplete-sfc  to install latest dependencies. I didnt see a network request either.
<img width="720" alt="screen shot 2019-01-17 at 9 47 43 am" src="https://user-images.githubusercontent.com/40767464/51326406-10e0b580-1a3d-11e9-91c4-8226dd922e6d.png">
<img width="1384" alt="screen shot 2019-01-17 at 9 47 51 am" src="https://user-images.githubusercontent.com/40767464/51326407-11794c00-1a3d-11e9-8469-fd1128b2daa4.png">

**Comment by rkatka** [comment]
I'm experiencing a similar issue.  I'm getting two build errors after running: `rm -rf node_modules && yarn install && npm run start --- autocomplete-sfc`: 
```
ERROR in [at-loader] ./exercises/autocomplete-sfc/tests/task.test.tsx:19:3
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'IterableIterator<number>' has no compatible call signatures.

ERROR in [at-loader] ./exercises/autocomplete-sfc/tests/task.test.tsx:32:3
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'IterableIterator<number>' has no compatible call signatures.
```

I'm able to hit the API link: `http://localhost:3000/maps/api/place/autocomplete/json?types=establishment&input=donut`

When I load up the the page after the build errors I'm getting a JS error:
`Uncaught SyntaxError: Unexpected token <` on line 1 of main.js

**Comment by mike-north** [comment]
Closing this issue because we've released a new version of the TypeScript course, where this is not a problem anymore
