### ISSUE TITLE
Exercise dict, branch v2-fem

### ISSUE THREAD

**Issue by laniehei** [mike-works/typescript-fundamentals#263]
- [X ] **Describe the bug**
`yarn test` produces errors, and the test does not pass when running the solution

- [ X] **To Reproduce**
Solution for dict exercise assumed to be located at [this location](https://github.com/mike-works/typescript-fundamentals/blob/v2-fem/challenges/dict/src/index.ts)

`yarn test` is run in challenges/dict. produces error shown in screenshot.

- [ X] **Screenshots (optional)**
<img width="1338" alt="Screen Shot 2019-03-15 at 3 56 08 PM" src="https://user-images.githubusercontent.com/13442634/54461566-ed836f80-473a-11e9-80f7-56c3fdfc3b2d.png">

**Comment by mike-north** [comment]
Fixes for this and a couple of other minor things in #264 . `v2-fem` branch has been updated, and tests should now pass on it

**Comment by mike-north** [comment]
Closing b/c #264 is merged. Please feel free to re-open if necessary
